stages:
  - build
  - publish
  - deploy
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
build-job:
  stage: build
  image: gradle:7.6.0-jdk17
  variables:
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - java -version
    - pwd
    - gradle clean
    - gradle bootJar
  artifacts:
    paths:
      - ./build/libs/
    expire_in: 1 day

build-docker-job:
  stage: publish
  image: docker:24.0.5
  variables:
    DOCKER_REGESTRY: "registry.docker.yummydo.top"
    DOCKER_USERNAME: "yummy"
    DOCKER_PASSWORD: "yummypwd"
  script:
    - docker --version
    - docker ps
    - pwd
    - ls
    - ls ./build/
    - ls ./build/libs/
    - mv ./build/libs/demo.jar app.jar
    - docker build -f ./Dockerfile -t registry.docker.yummydo.top/demo:latest .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGESTRY
    - docker push $DOCKER_REGESTRY/demo:latest

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production

#deploy_k8s:
#  image:
#    name: bitnami/kubectl:latest
#    entrypoint: [""]
#  before_script:
#    - cp -rf /build/kubeconfig/config /.kube/config
#  script:
#    - echo "deploy to k8s cluster..."
#    - kubectl version
#    - kubectl get pods --all-namespaces