spring:
  application:
    name: gateway
  cloud:
    gateway:
      x-forwarded:
        prefix-enabled: true
      routes:
        - id: test-service
          uri: lb://test-service
          predicates:
            - Path=/test/**, /v3/api-docs/test
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
            - StripPrefix=1
server:
  port: 9000
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


