spring:
  application:
    name: test-service

server:
  port: 9001
  forward-headers-strategy: framework
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka